### ISSUE TITLE
Images/Svgs from custom theme css are not handled properly in pdf export

### ISSUE THREAD

**Issue by hofbi** [marp-team/marp-cli#304]
**Problem Description**

Exporting slides to pdf results in missing or wrong displayed (location and size) images.

* This happens just for images which are specified in the `theme.css`. Images which are directly used in markdown work as expected. I use background images in the css to properly handle light and dark theme of my slides
* This happens only in the pdf export. For live serving and html generation everything works fine

**Steps to reproduce**

1. Set a background image in the custom theme css file, e.g.

```css
section
{
  background-color: #fff;
  color: #000;
  background-image: url('path_to_the_image');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: right 40px top 40px;
  background-size: 8%;
}
```

2. Export
   1. PDF to reproduce the error
   1. HTML to see the expected behavior
