### ISSUE TITLE
Transparent background does not work when outputting in png format

### ISSUE THREAD

**Issue by 50Bytes-dev** [marp-team/marp-cli#555]
I'm trying to make the slide background transparent when exporting to png. it doesn't work.

```css
section {
    background-color: transparent;
    width: 1920px;
    height: 1080px;
}

:root {
    background-color: transparent;
}
```

```shell
marp --theme custom.css test.md -o test.png
```
